name: test pull request ci

on:
  pull_request:
    types: [ opened, synchronize ]
    branches:
      - 'main'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  notify-slack-create-release-pr:
    if: github.event_name == 'pull_request' && github.event.action == 'opened' && startsWith(github.head_ref, 'release/')
    runs-on: ubuntu-latest
#    hoge, hoge
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: sample step
        run: echo "This is a sample step to demonstrate the workflow."
