name: test pull request ci

on:
  pull_request:
    types: [ opened, synchronize ]
    branches:
      - 'release/*'
      - '**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  notify-slack-create-release-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: sample step
        run: echo "This is a sample step to demonstrate the workflow."
